services:
  nasa-postgres:
    image: postgres:15
    container_name: nasa-apod-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: nasa_apod
    ports:
      - "5433:5432"
    volumes:
      - nasa-postgres-data:/var/lib/postgresql/data
    networks:
      - airflow

volumes:
  nasa-postgres-data:
    driver: local

networks:
  airflow:
    name: assignment-03_8c6823_airflow
    external: true
